### PR TITLE
Add in a dependency on spdlog_vendor.

### PR DESCRIPTION
**Pull request by clalancette**
That way when building on e.g. Windows, the paths to spdlog will be setup properly before trying to build this vendor package.

### CODE REVIEW

**Comment by clalancette** [comment]
@azeey FYI

**Comment by clalancette** [comment]
Pulls: https://github.com/gazebo-release/gz_utils_vendor/pull/6
Gist: https://gist.githubusercontent.com/clalancette/11847a66a3f19f2c5d5e06095eb9f2a5/raw/2869a3727fde4ad25d8bb20f1713dd9e5d58af02/ros2.repos
BUILD args:  --packages-above-and-dependencies gz_utils_vendor
TEST args:  --packages-above gz_utils_vendor
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14533
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21809/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16080/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1312/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22510/)

**Comment by clalancette** [comment]
Pulls: https://github.com/gazebo-release/gz_utils_vendor/pull/6
Gist: https://gist.githubusercontent.com/clalancette/b8a2f4e72261d8b92ce938a70e5d4557/raw/2869a3727fde4ad25d8bb20f1713dd9e5d58af02/ros2.repos
BUILD args:  --packages-above-and-dependencies gz_utils_vendor
TEST args:  --packages-above gz_utils_vendor
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14536
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21812/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/16083/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1315/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22513/)

**Review by azeey — APPROVED** [review]
Thanks Chris! I've updated the script that generates these and I believe it matches this PR: https://github.com/gazebo-tooling/gz_vendor/pull/9

**Comment by clalancette** [comment]
With CI green and an approval, I'm going to go ahead and merge this one.

**Comment by clalancette** [comment]
Oh!  Actually, I have no permissions here, @azeey can you go ahead and do it?  Thanks.

**Pull request merged**
